"""empty message

Revision ID: 9865b6429440
Revises: ed01b9f19862
Create Date: 2025-04-13 21:13:53.506243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9865b6429440'
down_revision: Union[str, None] = 'ed01b9f19862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('organizations', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('organizations', 'image_path')
    # ### end Alembic commands ###
