"""empty message

Revision ID: 8096509d7efb
Revises: e8a25398f003
Create Date: 2025-04-09 19:23:14.588227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8096509d7efb'
down_revision: Union[str, None] = 'e8a25398f003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_name'), 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_name'), 'users', type_='unique')
    # ### end Alembic commands ###
