"""empty message

Revision ID: 5383abe43c28
Revises: 38f57f0ed37e
Create Date: 2025-05-02 18:58:57.846934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5383abe43c28'
down_revision: Union[str, None] = '38f57f0ed37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('author_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_quizzes_author_id_users'), 'quizzes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quizzes_author_id_users'), 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'author_id')
    # ### end Alembic commands ###
