"""empty message

Revision ID: 20778a25f9c7
Revises: 8616853ece48
Create Date: 2025-05-07 22:54:25.637519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20778a25f9c7'
down_revision: Union[str, None] = '8616853ece48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_waiting_session_join_code', 'sessions', ['join_code'], unique=True, postgresql_where=sa.text("status = 'WAITING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_waiting_session_join_code', table_name='sessions', postgresql_where=sa.text("status = 'WAITING'"))
    # ### end Alembic commands ###
