"""Added current question index to session

Revision ID: fb107cbc11b2
Revises: 03f68ccb0383
Create Date: 2025-05-15 23:35:44.309985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb107cbc11b2'
down_revision: Union[str, None] = '03f68ccb0383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('current_question_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'current_question_index')
    # ### end Alembic commands ###
