"""empty message

Revision ID: 03f68ccb0383
Revises: 20778a25f9c7
Create Date: 2025-05-08 17:13:51.142551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f68ccb0383'
down_revision: Union[str, None] = '20778a25f9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_nickname', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('HOST', 'PARTICIPANT', name='participantrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_participants_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    op.create_table('participants_answers',
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=24), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_participants_answers_participant_id_participants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id', 'question_id', name=op.f('pk_participants_answers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants_answers')
    op.drop_table('participants')
    # ### end Alembic commands ###
