name: Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 8.0.6
          mongodb-replica-set: overleaf
          mongodb-container-name: mongo

      - name: Create mongo user
        run: |
          docker exec mongo mongosh --eval '
            db.getSiblingDB("admin").createUser({
              user: "mongo",
              pwd: "mongo",
              roles: [
                { role: "root", db: "admin" }
              ]
            })
          '
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: 8.0
          redis-password: 'somepassword'

      - name: Run tests
        run: uv run pytest -v --durations=0 --cov --cov-report=xml

    #   - name: Upload Coverage to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
