name: Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Start mongo with replica set and user
        run: |
          docker run --rm -d \
            -p 27017:27017 \
            --name mongo \
            -e MONGO_INITDB_ROOT_USERNAME=mongo \
            -e MONGO_INITDB_ROOT_PASSWORD=mongo \
            mongo:8.0.6 --replSet test --bind_ip_all

          sleep 10
          docker exec mongo mongosh -u mongo -p mongo --eval "rs.initiate()"

      - name: Run tests
        run: uv run pytest -v --durations=0 --cov --cov-report=xml

    #   - name: Upload Coverage to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
